version: "3.2"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: appsDB
    restart: always
    # networks:
    #   - febnine-net
    ports:
      - "3306:3306"
    env_file:
      - docker.env
    environment:
      TZ: Asia/Seoul
    volumes:
      - mysql:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password

  # mongo:
  #   image: mongo
  #   container_name: mongoDB
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  app:
    # networks:
    #   - febnine-net
    depends_on:
      - db
    # - mongo
    build:
      context: ./weather
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    ports:
      - "3000:3000" # Adjust the port as needed
    volumes:
      - ./weather:/weather
      - /weather/node_modules/
  # - /weather/dist/

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

# volumes:
#   mongo_data:
volumes:
  mysql:
# networks:
#   febnine-net:
#     driver: bridge
