version: "3.2"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: appsDB
    restart: always
    networks:
      - febnine-net
    ports:
      - "3306:3306"
    env_file:
      - docker.env
    environment:
      TZ: Asia/Seoul
      VERSION: PROD
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    networks:
      - febnine-net
    depends_on:
      - db
    build:
      context: ./weather
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    ports:
      - "3000:3000" # Adjust the port as needed
    volumes:
      - ./weather:/weather
      - /weather/node_modules/
    command:
      - bash
      - -c
      - |
        /weather/wait-for-it.sh appsDB:3306 -t 10
        npm run start
volumes:
  mysql:
networks:
  febnine-net:
    driver: bridge
